from typing import ClassVar, Self, final

@final
class SourcePosition:
    __match_args__ = ("index", "line", "column")
    __hash__: ClassVar[None]  # type: ignore[assignment]
    def __new__(cls, index: int, line: int, column: int) -> Self: ...
    @property
    def index(self) -> int: ...
    @property
    def line(self) -> int: ...
    @property
    def column(self) -> int: ...
    def __eq__(self, other: object, /) -> bool: ...

@final
class SourceSpan:
    __match_args__ = ("start", "end")
    __hash__: ClassVar[None]  # type: ignore[assignment]
    def __new__(cls, start: SourcePosition, end: SourcePosition) -> Self: ...
    @property
    def start(self) -> SourcePosition: ...
    @property
    def end(self) -> SourcePosition: ...
    def __eq__(self, other: object, /) -> bool: ...
